### PR TITLE
Simplifies PNG export, removes ChunkyPNG resizing

### PR DESCRIPTION
**Pull request by bjedrocha**
I've noticed that when specifying the `resize_exactly_to` option to `as_png` the resulting image would often be slightly distorted. For example, the following 

```
image = RQRCode::QRCode.new("http://facebook.com", level: :l).as_png(resize_exactly_to: 80)
```
would produce the image
chunky_resize
Notice the varying thickness around the position squares.

I've noticed that other QRCode generators (e.g. Google's now deprecated Charts API) don't have this issue so this is my attempt at fixing it.

This pull request removes the `resize_exactly_to` option in favour of `size` to make it more consistent with the other exporters. It also removes the call to ChunkyPNG's `resize` and instead accomplishes exact sizing by varying the amount of border space around the data portion of the code (similar to how Google's Chart API does it). So now, the following
```
image = RQRCode::QRCode.new("http://facebook.com", level: :l).as_png(size: 80)
```
will produce the image
simplified_resize

### CODE REVIEW

**Comment by bjornblomqvist** [comment]
Looks good =).

Could change so that resize_exactly_to is a alias for size so that we don't break any clients currently using it?

**Comment by bjedrocha** [comment]
Good idea. I've added backwards compatibility with 92126faf9d4c60ebda8bc85f238bbb67f44f8ccf. Thanks.

**Comment by bjornblomqvist** [comment]
Sorry that i missed it before, but do you think you could bring back the options :resize_gte_to and :module_px_size also? 

Without them we are still not backwards compatible.

**Comment by bjedrocha** [comment]
Hey sorry about that, I removed those in my version and I guess I forgot to add them back before making the pull-request. Those two options have been added back in and they retain the same functionality as before. Thanks for catching that.

**Comment by bjornblomqvist** [comment]
Sorry for being so slow.

I have taken your code and made some changes. Have a look and tell me what you think?

https://github.com/bjornblomqvist/rqrcode/tree/googleis-png-export

**Comment by bjedrocha** [comment]
No worries - I'm good with the changes you made, I tested them locally and everything worked as it should. I think you have a redundant `module_px_size` defined on [L58](https://github.com/bjornblomqvist/rqrcode/blob/d7948a92c8145f0a9d295ae086a27a344fcc6d73/lib/rqrcode/export/png.rb#L58) but other than that I think we're good. Thanks again for looking into this and your work with the project.

**Comment by bjornblomqvist** [comment]
New version out with your improvement.

**Pull request closed without merging**
